# Generated by Django 5.1.4 on 2024-12-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_delete_doctor_user_address_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
